[config]
local=yes
verbose=yes
testdir=tests

[features]
skip-if-tcc=!tcc

[exclude]
tests/empty.js
tests/fixture_cyclic_import.js
tests/microbench.js
tests/test_worker_module.js
tests/fixture_string_exports.js
tests/fixture_throwing_module.js
tests/fixture_reexport_source.js
tests/fixture_reexport_missing.js
tests/fixture_reexport_direct.js
tests/fixture_export_base.js
tests/fixture_export_empty.js
tests/fixture_export_empty2.js
tests/fixture_export_from.js
tests/fixture_export_hub_ambiguous.js
tests/fixture_export_hub_ns_ambiguous.js
tests/fixture_export_hub_ns_import_ok.js
tests/fixture_export_hub_ns_mixed_ok.js
tests/fixture_export_hub_ns_ok.js
tests/fixture_export_hub_ok.js
tests/fixture_export_import_and_export.js
tests/fixture_export_ns_import_1.js
tests/fixture_export_ns_import_2.js
tests/fixture_export_ns_other.js
tests/fixture_export_ns_star_as_1.js
tests/fixture_export_ns_star_as_2.js
tests/fixture_export_other.js
tests/fixture_export_renamed.js
tests/fixture_export_hub_ambiguous_use.js
tests/fixture_export_hub_ns_ambiguous_use.js
tests/fixture_export_hub_partial.js
tests/fixture_export_only_second.js
